### ISSUE TITLE
"No integration delete" error

### ISSUE THREAD

**Issue by karaspr** [chomupashchuk/delete-file-home-assistant#11]
Hi, I got error like in the title after adding "delete:" line in configuration.yaml. What am I doing wrong?

**Comment by chomupashchuk** [comment]
According to the description it sounds like HA is not aware of the integration.
At first you have to copy folder in /config/custom_components, then restart HA so that it scans and finds the integration as such. Then you can add string to configuration.yaml (at this point HA knows which integration it is and format of data it requires) and I believe another restart is needed to see new services, but not sure.

I usually include needed data and restart HA container in Docker (not Hassio), so that custom components folder is scanned and configuration.yaml parsed during one start. This way configuration.yaml is not checked before the restart, but it brings risks of errors.

**Comment by chomupashchuk** [comment]
I suspect that it is installation issues. I have updated README.MD.
