### ISSUE TITLE
multiple folder

### ISSUE THREAD

**Issue by sunsgs** [chomupashchuk/delete-file-home-assistant#2]
Is it possible to delete multiple folders or all files in folder and all subfolders?

**Comment by chomupashchuk** [comment]
Removing folders is not the same functions as removing files. The intention of the integration was to clean up files within root of directory like snapshots and videos, where folder can stay as it is. Folder is expected to be filled in with similar files again. Since the intention was to deal with only few actions that create files (so only few folders), it should not have been a problem to trigger actions in automation for few times per folder.

Please provide the use cases of removing multiple folders and sub-folders and multiple folders. 
I do not have much free time lately due to changes at work and would like to avoid doing something that i do not see any value in. For example if someone would like to use integration as one time only cleanup action. In reality HA is on linux system and there are ways to do it via command line or similar. What would be the benefit in having it as an integration, which has no file explorer, not tree view, and what if it to be used by only one person?

So please describe why would you need those options with examples.

**Comment by chomupashchuk** [comment]
Subfolders handling added
